/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { LostItem, VerificationClaim, User } from './types';

export const DEFAULT_USERS: User[] = [
  {
    id: '20241001',
    name: 'Alex Rivera',
    email: 'alex.rivera@university.edu',
    role: 'student',
    department: 'Engineering Department',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=150',
  },
  {
    id: '20241002',
    name: 'Sarah Chen',
    email: 'sarah.chen@university.edu',
    role: 'student',
    department: 'Computer Science Department',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150',
  },
  {
    id: '20241003',
    name: 'Jordan Peterson',
    email: 'jordan.p@university.edu',
    role: 'student',
    department: 'Business & Management',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150',
  },
  {
    id: '20241004',
    name: 'Mia Thompson',
    email: 'mia.t@university.edu',
    role: 'student',
    department: 'Humanities & Fine Arts',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=150',
  },
  {
    id: 'admin',
    name: 'Director Richard Vance',
    email: 'admin.vance@university.edu',
    role: 'admin',
    department: 'Campus Security & Administration',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAc0lxKEWhOvDX5pSLNMZ5Acivuq2jS0wqb0zAK89IpXwQcVGUihlTyxghhGo4PY9mXnMcGE-SxCiCHAoHJ-ExOs1rvty8mJRF3Xno0X7u6tZUa_rf7kwLJDqqfpzqO0P815NMAX5zD13CLpyqObS0ldyBrk_vLwXXimDo8UQYgkPT9KQfpA8P9Tu5WLZT-VwXWiMe9d2h9NntDpwO6ZZZXHrWw3QkAO4ZMjyfglGMANwOwGWQ9f13IGj2nA2TC47YTkHvezYaIog',
  },
];

export const DEFAULT_ITEMS: LostItem[] = [
  {
    id: 'item-1',
    type: 'found',
    name: 'Apple iPad Air',
    category: 'Electronics',
    location: 'Central Library, Floor 2',
    date: '2026-06-15',
    description: 'Space Gray iPad Air with a stylus attached on the side. Found resting on a clean wooden study table.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC-A25-5_ATWeRIL4WUWiuxRKFGU3S1RTHbkOc_0xlkF6QSCd3x0PQyiY9NIKtwKUxJKVxB2LHEuhFhHhVp92DH2I_sQ5LyQu0fie-ssVSWimajfrag2zAtjssmhf9ecHzFzYGr-zBhkMr1EgZ9R2tOadNZj7GpraTOJUanvC3_zWcOxixhskJ80TO7DT_XwrGcCta1HvWRbUgWp_0jprwQqzIRdJ4b8KPcJntU3sxkSY8K3Tki50TkCmsKE8h9AWfwzVEBbG9dfA',
    reporterId: 'admin',
    reporterName: 'Campus Security Office',
    contactNo: '+1 (555) 019-0000',
    status: 'found',
    createdAt: '2h ago',
  },
  {
    id: 'item-2',
    type: 'lost',
    name: 'Blue Water Bottle',
    category: 'Personal Items',
    location: 'Sports Complex Gym',
    date: '2026-06-14',
    description: 'Stainless steel high-quality water bottle in navy blue colour, stands on grey concrete of campus walkway.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBLPiVL9K2dNKpZvTFlnL68udWhACBTJ0CPl7u9JNQR6Ghb_5rwc_zLaqw8YZ5tNmQVScuGDOmf7buL50oiIW2K1tfyN0W1vKGvWx3EPoTonNMRM5iv2LRObZKKLD5NZ93jXzxHC7qW3wWWwrG3OvkwMIcB8o4tFwRddjGV_ofesG-l-ywyhr_Dzh2d98fIuOy2L8w3VG6bUeBE0gPumfJHCIxELikQpbfs8FLl0ug8zy8tyvWppjFS2Yi93CKNzCjKM0D5UdUauA',
    reporterId: '20241003', // Jordan Peterson
    reporterName: 'Jordan Peterson',
    contactNo: '+1 (555) 019-2234',
    status: 'lost',
    createdAt: 'Yesterday',
  },
  {
    id: 'item-3',
    type: 'lost',
    name: 'House Keys',
    category: 'Others',
    location: 'Student Union Lounge',
    date: '2026-06-13',
    description: 'Keychain with brown leather fob and three silver keys attached next to an open notebook.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDX6rL4SoJiTZM2M5un_eYoXwrucFLNYWGIWt1fpLqeY3fBRkB4VdJGDFFQ5vj0J46Ybk00u1r2EkJR2PSWwSx-WFVOElz1XxiX9exnL5zJDDbWfWKTCCo5IVbFXC6yjUEWo0LsYEBq6gOa1DKIvAR4uBbe_k4E5DNSDBmBs74eZ1M28IWAJyuCKCgP4yEo3msJpML3P-PdqCGrlOxtsi005r5KKVRR3cJqAofkILon0L4z0_nejCqxqGqDzy3fey5Tff2qBX_bJg',
    reporterId: '20241001', // Alex Rivera
    reporterName: 'Alex Rivera',
    contactNo: '+1 (555) 011-8899',
    status: 'pending',
    createdAt: 'Oct 24',
  },
  {
    id: 'item-4',
    type: 'found',
    name: 'Dell Laptop Charger',
    category: 'Electronics',
    location: 'Engineering Block B',
    date: '2026-06-12',
    description: 'Regular Dell 65W AC power adapter with coiled black cables, found on white library/study table.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCyBTjtgf8Hml6AKNP42qHrotYKjDdq4CQqsJsDf1Oag6YLJcS_Oen0ezSRcCMV3SLIYo2jgEc9DMAYFl4qdRDz9bTvjiurFrf4jSsal5dirVd9pAKjpkzknD4zeXA_hhUdTJzgZR-mNUtgkos5ekVLR9vcuolPmoKzopP78oT2cgByhYS4hssRnoRAlPB8jRM53twfoILg4LaQ90k6vRAc0y2rLbAHehUP0uPhhd2WaeKoOKMu-pzZQJz_0QQHzbxq8PG1q_YCSw',
    reporterId: 'admin',
    reporterName: 'Security Officer Smith',
    contactNo: '+1 (555) 019-0011',
    status: 'found',
    createdAt: '3d ago',
  },
  {
    id: 'item-5',
    type: 'lost',
    name: 'Black Hoodie',
    category: 'Clothing',
    location: 'Main Auditorium',
    date: '2026-06-08',
    description: 'Plain black cotton hoodie folded neatly. Size L with custom embroidery on the left sleeve cuffs.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAAUv37f55Ru-vUhvaBXxLr9a-wUpmMUw4t_fFIajiSw8K5m4_RGNH0iNQAH_69lvgtnrwFhhWdGcdHLu4taRQTaEJdm1mhO7c5cS9jIMHGhe8Za5UQCdtJg7VdnNamFQFQajaPgWNmkIdxCl4Kmcl5_47jxOp9WyTl7lS6NkQuL-ryjjLKiXDQGn9wPK8ePagPK9i5NG5IvP9EOM8_tLQbQBQEulZ-M3RmHQvgnBuWXB2le6iG98G9ohy_aOrZWs0cmglfNyTFNw',
    reporterId: '20241004', // Mia Thompson
    reporterName: 'Mia Thompson',
    contactNo: '+1 (555) 018-4433',
    status: 'lost',
    createdAt: '1w ago',
  },
  {
    id: 'item-6',
    type: 'found',
    name: 'Parker Pen',
    category: 'Stationery',
    location: 'Humanities Hall 102',
    date: '2026-06-15',
    description: 'Black and silver Parker fountain pen resting on a dark navy journal. Left behind at the podium.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBHSeqC0REmbvBT4TymXVxTHoboameZH53RWBTm8Gv5BD6N6CSeF85UYOw1VB3QXQrUXGh5Nim8llw6ANxjHslQYE1wkYpPM0yxMtQC2riDE_gvQxk0zqTb8Kp0ZtPp1gzTxY4oerlgJbWIs8sAUY_y99qkBCy4U_VuuvRg_prrF6nj-5hqORlPAjv4E3j54Hcr53vJTuwtO4Hz1PU1rAupUg0EQb7abW9vUeGUSOHXOFlxPfhqkjOVxLHIuPV5MxWDMInV7_a4TQ',
    reporterId: 'admin',
    reporterName: 'Prof. Abernathy',
    contactNo: '+1 (555) 014-1122',
    status: 'found',
    createdAt: 'Today',
  },
];

export const DEFAULT_CLAIMS: VerificationClaim[] = [
  {
    id: 'claim-1',
    itemId: 'item-101', // Virtual iPhone item
    itemName: 'iPhone 13 Pro',
    itemImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBIU7aww5KgZ5tQjTf_R9G0xkPuG9P2eeUMiT_RWp8BR2u64lddLmkgCLqPfxxVC5LrUxNgumLcmu3ny0gAO8UNTYLSqgln8mzYi0yI3XzFh9tW44TWu1l6moJVE7HzVg3OmBdwkLxKzD-QB8fl-IeiLVvnyvpdJYaQnkwmDmwEZhly0VlPnFoOchMOCK28V-Zzs2w8OeVDtPPRXbrTaI3y188sqpvoMVeohnVFwQQP32T2JhODlNaXr3GbvHSaZJ_EPIaa4cQ1qA',
    claimantId: '20241001',
    claimantName: 'Alex Rivera',
    claimantStudentId: '20241001',
    description: 'I left my iPhone 13 Pro in the Student Union cafeteria near the window around 2 PM. It has a clear case with a sticker of a Shiba Inu on the back. FaceID should unlock to my face Alex Rivera.',
    timestamp: '2h ago',
    status: 'pending',
    locationMatch: true,
  },
  {
    id: 'claim-2',
    itemId: 'item-102', // Virtual Sony Headphones
    itemName: 'Sony WH-1000XM4',
    itemImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCY4LfPj9v9QyJ6-VgXccx3cnnr_XiTSVXBFdnvxODLZK8KjS0gvmXoxQ6ghe5ej16_G-AejQTgwh1QR16h_W-XXbWsJwXqWywqC84FSUgupJUPiuV7SlD0fqy4kQUTMNvGTeck99HhjC-nszPo-qjOE1uMWPYe0swc3-ejkhg8Codc0vLs-8q-r1imgqXLaytlL9ddyK1MKQ2bZnREZmi182cBjXuTI2CMiGTbCeN8L7CcU7iH_VsQi41J-zzibI04K_yRLVfVyA',
    claimantId: '20241002',
    claimantName: 'Sarah Chen',
    claimantStudentId: '20241002',
    description: 'Silver color, missing the audio cable inside the black carrying case. I lost them in the Main Library Level 3 quiet zone on the far left cubicle.',
    timestamp: '5h ago',
    status: 'pending',
    locationMatch: true,
  },
  {
    id: 'claim-3',
    itemId: 'item-103', // Virtual Wallet
    itemName: 'Brown Leather Wallet',
    itemImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD__-5YgNW8XyH4mi-vvu9tkYSVCPizOAtzkRW97JUiy-LVUysrgPsESEpppFWeW0WZGNCQRbnYKNIWugu4pt6_ks17X0Lqxfr_iAIu1eTbuCjeXQoJLV_-frSu3Bs1e4qtvYxNpOO367oDqvoO98pRE9YFSrsEQ8S2VkI8VVfIM_NWpc_A3e2lAKRBTC1LmAdc97kigNjOVgqP5Bu0_jVdbk2B25BrYLNzNCfZESNpAOAUqrCvK_oaUzfbAue8WUKurcSnxNPcOQ',
    claimantId: '20241003',
    claimantName: 'Jordan Peterson',
    claimantStudentId: '20241003',
    description: 'Contains a student ID with my name and a gym membership card. There is a small tear near the logo and exactly 15 dollars inside.',
    timestamp: '1d ago',
    status: 'pending',
    locationMatch: true,
  },
  {
    id: 'claim-4',
    itemId: 'item-104', // Virtual Earbuds
    itemName: 'Wireless Earbuds',
    itemImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA4o3LWXX_ZrB9c3w4hrFTotAhOlfRFMVy2R6QXV_r5J8Lv87pzm2MgtO6kylchsvSJO82CpaYKgBjH8KgT28o4YsekLf8VjBIgzy5q82jEamdIxuNeMrOCoZM-ImdVVAP8XLQtGjT3E7itHx-DPJY_jwzq10pM4977oFX0TCh-ImGrJwIePmlJ-jcbkMxPbnEA-7Bn99BdKkmEL0VBQLSTk3DgtYbV64JKVMWlhauxZh5BRZE3TkeibPUTYdBbLANlQaJtZE9nKg',
    claimantId: '20241004',
    claimantName: 'Mia Thompson',
    claimantStudentId: '20241004',
    description: 'The right bud has a slight scratch on the touch panel. I lost them in the Gym locker room area after basketball practice around 6 PM.',
    timestamp: 'Yesterday',
    status: 'pending',
    locationMatch: true,
  },
];
